servingEngineSpec:
  enableEngine: true
  runtimeClassName: nvidia

  labels:
    environment: inference
    release: inference

  serviceMonitor:
    enabled: true

  modelSpec:
    - name: qwen25-1-5b
      enabled: true
      runtimeClassName: nvidia

      repository: vllm/vllm-openai
      tag: v0.23.0
      imagePullPolicy: IfNotPresent

      modelURL: Qwen/Qwen2.5-1.5B-Instruct
      replicaCount: 1

      requestCPU: 2
      requestMemory: 8Gi
      limitCPU: 4
      limitMemory: 16Gi

      requestGPU: 1
      requestGPUType: nvidia.com/gpu

      pvcStorage: 20Gi
      storageClass: local-path
      shmSize: 8Gi

      enableLoRA: false

      lmcacheConfig:
        enabled: false

      keda:
        enabled: false

      vllmConfig:
        enablePrefixCaching: true
        enableChunkedPrefill: true
        maxModelLen: 8192
        dtype: bfloat16
        tensorParallelSize: 1
        maxNumSeqs: 32
        gpuMemoryUtilization: 0.80
        runner: auto
        extraArgs: []

routerSpec:
  enableRouter: true
  repository: lmcache/lmstack-router
  tag: v0.1.11
  imagePullPolicy: IfNotPresent

  replicaCount: 1
  serviceType: ClusterIP
  servicePort: 80
  serviceDiscovery: k8s
  k8sServiceDiscoveryType: pod-ip
  routingLogic: roundrobin

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

  serviceMonitor:
    enabled: true
    interval: 15s
