apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: "18.7.13"
      helm:
        valueFiles:
          - $values/deploy/data/postgresql-values.yaml
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: redis
      targetRevision: "27.0.15"
      helm:
        valueFiles:
          - $values/deploy/data/redis-values.yaml
    - repoURL: https://zilliztech.github.io/milvus-helm
      chart: milvus
      targetRevision: "5.0.24"
      helm:
        valueFiles:
          - $values/deploy/data/milvus-values.yaml
    - repoURL: https://github.com/GUGA12/llm-infra-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
