apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: "2.20.1"
      helm:
        releaseName: keda
    - repoURL: https://github.com/GUGA12/llm-infra-platform.git
      targetRevision: main
      path: deploy/inference
      directory:
        include: keda-scaledobject.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
